services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        - http_proxy=${http_proxy:-}
        - https_proxy=${https_proxy:-}
        - HTTP_PROXY=${HTTP_PROXY:-}
        - HTTPS_PROXY=${HTTPS_PROXY:-}
    network_mode: host
    environment:
      - http_proxy=${http_proxy:-}
      - https_proxy=${https_proxy:-}
      - HTTP_PROXY=${HTTP_PROXY:-}
      - HTTPS_PROXY=${HTTPS_PROXY:-}
      - no_proxy=${no_proxy:-}
      - NO_PROXY=${NO_PROXY:-}
