import os
import json
import csv
import sys
import importlib.util
from datetime import datetime
from pathlib import Path

REPORT_PATH = "/app/report.json"
FUEL_CALC_PATH = "/app/fuel_calc.py"
VEHICLES_PATH = "/app/data/vehicles.json"
TRIPS_PATH = "/app/data/trips.csv"
PRICES_PATH = "/app/data/fuel_prices.csv"


def load_fuel_calc():
    spec = importlib.util.spec_from_file_location("fuel_calc", FUEL_CALC_PATH)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def parse_date(d):
    return datetime.strptime(d, "%Y-%m-%d")


def compute_expected():
    """Oracle logic to compute expected report - independent of agent's generate_report.py"""
    with open(VEHICLES_PATH) as f:
        vehicles = {v["id"]: v for v in json.load(f)}

    prices = []
    with open(PRICES_PATH) as f:
        reader = csv.DictReader(f)
        for row in reader:
            prices.append((parse_date(row["date"]), float(row["price_per_gallon"])))
    prices.sort(key=lambda x: x[0])

    def get_price(trip_date):
        cand = None
        for pd, pp in prices:
            if pd <= trip_date:
                cand = pp
            else:
                break
        if cand is None:
            cand = prices[0][1] if prices else 0.0
        return cand

    per_vehicle = {vid: {"total_miles": 0.0, "total_fuel_gallons": 0.0, "total_cost": 0.0} for vid in vehicles}

    with open(TRIPS_PATH) as f:
        reader = csv.DictReader(f)
        for row in reader:
            vid = row["vehicle_id"]
            if vid not in vehicles:
                continue
            miles = float(row["miles"])
            td = parse_date(row["date"])
            mpg = vehicles[vid]["mpg"]
            fuel = miles / mpg
            price = get_price(td)
            cost = fuel * price
            per_vehicle[vid]["total_miles"] += miles
            per_vehicle[vid]["total_fuel_gallons"] += fuel
            per_vehicle[vid]["total_cost"] += cost

    for vid in per_vehicle:
        per_vehicle[vid]["total_miles"] = round(per_vehicle[vid]["total_miles"], 2)
        per_vehicle[vid]["total_fuel_gallons"] = round(per_vehicle[vid]["total_fuel_gallons"], 2)
        per_vehicle[vid]["total_cost"] = round(per_vehicle[vid]["total_cost"], 2)

    fleet_total = round(sum(v["total_cost"] for v in per_vehicle.values()), 2)

    most_inefficient = None
    max_ratio = -1
    for vid, stats in per_vehicle.items():
        if stats["total_miles"] > 0:
            ratio = stats["total_fuel_gallons"] / stats["total_miles"]
            if ratio > max_ratio:
                max_ratio = ratio
                most_inefficient = vid

    return {
        "per_vehicle": per_vehicle,
        "fleet_total_cost": fleet_total,
        "most_inefficient_vehicle": most_inefficient,
    }


def test_report_exists():
    assert os.path.exists(REPORT_PATH), f"{REPORT_PATH} must exist - generated by step 2"


def test_report_valid_json():
    with open(REPORT_PATH) as f:
        data = json.load(f)
    assert isinstance(data, dict)


def test_report_schema():
    with open(REPORT_PATH) as f:
        data = json.load(f)
    assert "per_vehicle" in data, "report must have per_vehicle"
    assert "fleet_total_cost" in data, "report must have fleet_total_cost"
    assert "most_inefficient_vehicle" in data, "report must have most_inefficient_vehicle"
    assert isinstance(data["per_vehicle"], dict)
    assert len(data["per_vehicle"]) == 3, "should have 3 vehicles"


def test_fuel_calc_still_exists_and_usable():
    # Context-following check: fuel_calc.py from step 1 must still exist after step 2
    assert os.path.exists(FUEL_CALC_PATH), "fuel_calc.py from step 1 must still exist in step 2"
    mod = load_fuel_calc()
    assert hasattr(mod, "calculate_fuel_needed")
    assert hasattr(mod, "calculate_cost")
    assert abs(mod.calculate_fuel_needed(100, 25) - 4.0) < 0.001


def test_report_uses_fuel_calc_import():
    """STRICT reuse check: Step 2 must import or invoke /app/fuel_calc.py via AST + string analysis."""
    found = False
    reuse_details = []
    checked_files = []

    for py_file in Path("/app").glob("*.py"):
        if py_file.name == "fuel_calc.py":
            continue
        checked_files.append(py_file.name)
        try:
            txt = py_file.read_text()
        except Exception:
            continue

        # AST-based checks
        try:
            import ast
            tree = ast.parse(txt)
            for node in ast.walk(tree):
                if isinstance(node, ast.Import):
                    for alias in node.names:
                        if "fuel_calc" in alias.name:
                            found = True
                            reuse_details.append(f"{py_file.name}: import {alias.name}")
                if isinstance(node, ast.ImportFrom):
                    if node.module and "fuel_calc" in node.module:
                        found = True
                        reuse_details.append(f"{py_file.name}: from {node.module} import ...")
                # Detect importlib.util.spec_from_file_location(..., "/app/fuel_calc.py") pattern via string in Call args not easy via AST, fallback to string check below
        except Exception:
            pass

        # String heuristic - import + usage
        if "fuel_calc" in txt and any(k in txt for k in ["calculate_fuel_needed", "calculate_cost", "importlib", "spec_from_file_location"]):
            found = True
            reuse_details.append(f"{py_file.name}: contains fuel_calc + usage keyword")
        # Subprocess CLI reuse is also valid
        if "fuel_calc.py" in txt and "subprocess" in txt:
            found = True
            reuse_details.append(f"{py_file.name}: subprocess calling fuel_calc.py")

    assert found, (
        "REUSE CHECK FAILED: Step 2 must import or invoke /app/fuel_calc.py from Step 1.\n"
        "Expected to find in /app/*.py (excluding fuel_calc.py) either:\n"
        "  - import fuel_calc via importlib.util.spec_from_file_location('fuel_calc', '/app/fuel_calc.py') and use calculate_fuel_needed/calculate_cost\n"
        "  - or subprocess.run(['python3', '/app/fuel_calc.py', ...])\n"
        f"Checked files in /app: {checked_files}\n"
        f"Reuse details found: {reuse_details}\n"
        "Do not re-implement formulas distance/mpg manually without importing fuel_calc."
    )


def test_per_vehicle_totals_miles():
    expected = compute_expected()
    with open(REPORT_PATH) as f:
        actual = json.load(f)
    for vid in expected["per_vehicle"]:
        assert vid in actual["per_vehicle"], f"{vid} missing in report"
        exp_miles = expected["per_vehicle"][vid]["total_miles"]
        act_miles = actual["per_vehicle"][vid]["total_miles"]
        assert abs(exp_miles - act_miles) < 0.05, f"{vid} total_miles mismatch: expected {exp_miles}, got {act_miles}"


def test_per_vehicle_fuel_gallons():
    expected = compute_expected()
    with open(REPORT_PATH) as f:
        actual = json.load(f)
    for vid in expected["per_vehicle"]:
        exp = expected["per_vehicle"][vid]["total_fuel_gallons"]
        act = actual["per_vehicle"][vid]["total_fuel_gallons"]
        assert abs(exp - act) < 0.05, f"{vid} total_fuel_gallons mismatch: expected {exp}, got {act}"


def test_per_vehicle_cost():
    expected = compute_expected()
    with open(REPORT_PATH) as f:
        actual = json.load(f)
    for vid in expected["per_vehicle"]:
        exp = expected["per_vehicle"][vid]["total_cost"]
        act = actual["per_vehicle"][vid]["total_cost"]
        assert abs(exp - act) < 0.10, f"{vid} total_cost mismatch: expected {exp}, got {act}. Check price lookup uses most recent <= date."


def test_fleet_total_cost():
    expected = compute_expected()
    with open(REPORT_PATH) as f:
        actual = json.load(f)
    assert abs(expected["fleet_total_cost"] - actual["fleet_total_cost"]) < 0.15, \
        f"fleet_total_cost mismatch: expected {expected['fleet_total_cost']}, got {actual['fleet_total_cost']}"


def test_most_inefficient_vehicle():
    expected = compute_expected()
    with open(REPORT_PATH) as f:
        actual = json.load(f)
    # V003 has lowest mpg (15.2) -> highest fuel per mile
    assert actual["most_inefficient_vehicle"] == expected["most_inefficient_vehicle"], \
        f"most_inefficient_vehicle mismatch: expected {expected['most_inefficient_vehicle']}, got {actual['most_inefficient_vehicle']}"
    assert actual["most_inefficient_vehicle"] == "V003", "With given mpgs, V003 (15.2 mpg) should be most inefficient"


def test_price_lookup_most_recent_logic():
    # Specific edge: trip on 2024-01-04 should use price from 2024-01-03 (3.52), not 2024-01-01 or 2024-01-06
    # Trip V002 150.75 miles on 2024-01-04, mpg 18, fuel 8.375, price 3.52 => cost 29.48
    trip_date = parse_date("2024-01-04")
    prices = []
    with open(PRICES_PATH) as f:
        reader = csv.DictReader(f)
        for row in reader:
            prices.append((parse_date(row["date"]), float(row["price_per_gallon"])))
    prices.sort(key=lambda x: x[0])
    cand = None
    for pd, pp in prices:
        if pd <= trip_date:
            cand = pp
        else:
            break
    assert abs(cand - 3.52) < 0.001, f"Price lookup logic wrong: expected 3.52 for 2024-01-04, got {cand}"

    # Check report total cost reflects this logic (not exact match lookup)
    with open(REPORT_PATH) as f:
        actual = json.load(f)
    assert actual["per_vehicle"]["V002"]["total_cost"] > 0


def test_price_lookup_2024_01_04_must_use_3_52_exact_failure_message():
    """Critical separate test: Trip on 2024-01-04 has no price entry, must use most recent <= which is 2024-01-03 $3.52.
    If agent used exact match, price lookup fails or returns wrong price, costing $ off by ~$10-15."""
    trip_date = parse_date("2024-01-04")
    prices = []
    with open(PRICES_PATH) as f:
        reader = csv.DictReader(f)
        for row in reader:
            prices.append((parse_date(row["date"]), float(row["price_per_gallon"])))
    prices.sort(key=lambda x: x[0])
    cand = None
    for pd, pp in prices:
        if pd <= trip_date:
            cand = pp
        else:
            break
    assert cand is not None, "Price lookup returned None - need fallback logic"
    assert abs(cand - 3.52) < 0.001, (
        f"PRICE LOOKUP FAILED: Trip on 2024-01-04 must use price from 2024-01-03 ($3.52) as most recent <=. "
        f"Got {cand}. Did you use exact date match instead of most-recent-<=? "
        f"Prices are sparse: 2024-01-04 has no entry, so you must look back to 2024-01-03."
    )
    # Also check report's V002 cost reflects this - if exact match used, V002 total would be wrong
    expected = compute_expected()
    with open(REPORT_PATH) as f:
        actual = json.load(f)
    exp_v002 = expected["per_vehicle"]["V002"]["total_cost"]
    act_v002 = actual["per_vehicle"]["V002"]["total_cost"]
    assert abs(exp_v002 - act_v002) < 0.10, (
        f"V002 cost mismatch suggests price lookup bug: expected {exp_v002} (using 3.52 for 2024-01-04), "
        f"got {act_v002}. Trip V002 on 2024-01-04 must use 2024-01-03 price 3.52, not 0 or next price."
    )


def test_price_lookup_fallback_before_first_price():
    """Fallback nuance: Trip before first price entry (e.g., 2023-12-31) must use first price 2024-01-01 $3.45"""
    early_date = parse_date("2023-12-31")
    prices = []
    with open(PRICES_PATH) as f:
        for row in csv.DictReader(f):
            prices.append((parse_date(row["date"]), float(row["price_per_gallon"])))
    prices.sort(key=lambda x: x[0])
    cand = None
    for pd, pp in prices:
        if pd <= early_date:
            cand = pp
        else:
            break
    if cand is None:
        cand = prices[0][1] if prices else 0.0
    assert abs(cand - 3.45) < 0.001, (
        f"FALLBACK PRICE LOOKUP FAILED: Trip on 2023-12-31 is before first price entry 2024-01-01, "
        f"so should use first price 3.45. Got {cand}. Did you handle candidate is None fallback?"
    )
    # If trips.csv contains early date, ensure report includes it
    with open(TRIPS_PATH) as f:
        has_early = any(row["date"] == "2023-12-31" for row in csv.DictReader(f))
    if has_early:
        expected = compute_expected()
        with open(REPORT_PATH) as fl:
            actual = json.load(fl)
        # V001 includes early trip now
        assert actual["per_vehicle"]["V001"]["total_miles"] >= expected["per_vehicle"]["V001"]["total_miles"] - 0.1, (
            f"Early trip 2023-12-31 not reflected: expected V001 miles >= {expected['per_vehicle']['V001']['total_miles']}, "
            f"got {actual['per_vehicle']['V001']['total_miles']}"
        )


def test_rounding_to_2_decimals():
    with open(REPORT_PATH) as f:
        data = json.load(f)
    for vid, stats in data["per_vehicle"].items():
        for k in ["total_miles", "total_fuel_gallons", "total_cost"]:
            val = stats[k]
            # Check rounded to 2 decimals by string representation
            s = f"{val:.2f}"
            # Ensure value has at most 2 decimal places
            assert abs(val - round(val, 2)) < 0.001, f"{vid} {k} not rounded to 2 decimals: {val}"
    assert abs(data["fleet_total_cost"] - round(data["fleet_total_cost"], 2)) < 0.001


def test_report_not_hardcoded_empty():
    with open(REPORT_PATH) as f:
        data = json.load(f)
    # Sanity: totals should be >0
    assert data["fleet_total_cost"] > 100, "fleet total cost seems too low, check calculation"
    for vid in data["per_vehicle"]:
        assert data["per_vehicle"][vid]["total_miles"] > 0
        assert data["per_vehicle"][vid]["total_fuel_gallons"] > 0
